syntax = "proto3";

package api;

service InternalService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc CreateApiKey(CreateApiKeyRequest) returns (CreateApiKeyResponse);
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string jwt = 1;
}

message ApiKey {
  string id = 1;
  string name = 2;
  bool is_admin = 3;
  string tenant_id = 4;
  bool is_read_only = 5;
}

message CreateApiKeyRequest {
  ApiKey api_key = 1;
}

message CreateApiKeyResponse {
  string id = 1;
  string token = 2;
}
